### ISSUE TITLE
code extension not generating .cs code template

### ISSUE THREAD

**Issue by NanaKay007** [microsoft/Windows-Machine-Learning#269]
## I'm submitting a…

 Bug report (I searched for similar issues and did not find one) 

## Current behavior

Importing an ONNX file doesn't generate the template code

## Expected behavior

should generate template code

## Minimal reproduction of the problem with instructions

I just imported the onnx file (version 1.3) into the assets folder of my project.

## Environment

Windows Build Number: version 1903

App min and target version: 1809 and 1903

OS Version (Server, IoT Core, Desktop, etc): Desktop

Graphics Driver version: Intel(R) UHD  23.20.16.4905

DxDiag: directX 12

WinMLTools specific:
	- Source training framework: Keras Tensorflow
        - WinMLTools version: 0.6.1 (Preview)

Visual Studio 
VS 2019

**Comment by LPBourret** [comment]
Hi,
first to confirm with you, is the *[Windows Machine Learning Code Generator](https://marketplace.visualstudio.com/items?itemName=WinML.MLGenV2)* Visual Studio extension installed in your VS2019 environment? Note that since Windows 10 1903 and later SDKs, this component (also called mlgen) is [not installed by default](https://docs.microsoft.com/en-us/windows/ai/windows-ml/mlgen).
thanks

**Comment by LPBourret** [comment]
closing, feel free to reopen
