### ISSUE TITLE
Passing input from GPU for inference

### ISSUE THREAD

**Issue by solarflarefx** [microsoft/Windows-Machine-Learning#292]
I am working in a pipeline architecture where all intermediary data resides in the GPU. I am interested in passing data already in the GPU into a DL network with the output still residing in the GPU to be passed to the next element in a pipeline. Essentially I would like to pass a cuda array into the network, get an output and convert back into a cuda array. I’d like to do this without having to perform CPU/GPU copies. Is this possible with WindowsML within C#?

**Comment by martinb35** [comment]
hello,
Windows ML does not interop with cuda arrays, but does with DirectX resources. Take a look at one of our tests [here](https://github.com/microsoft/onnxruntime/blob/master/winml/test/scenario/cppwinrt/scenariotestscppwinrt.cpp#L440) that does what you are trying to do (no cpu/gpu copies), but in C++. Because Windows ML and DirectML sit on top of DirectX, and DirectX does not expose this kind of functionality through C#, it must be done with C++.
