### ISSUE TITLE
evaluateasyn sample and explanation

### ISSUE THREAD

**Issue by anagharao21** [microsoft/Windows-Machine-Learning#321]
## I'm submitting a…

Bug report (I searched for similar issues and did not find one)

## Current behavior

I want to have 2 evaluates running parallelly on 2 different devices(and 2 different sessions) that I have created, for which I am using EvaluateAsync() 
Code:

	std::cout<<"			Starting Evaluate			" << std::endl;

	    auto start = high_resolution_clock::now();

	    auto eval_1= session.EvaluateAsync(binding, L""();
        auto eval_2 = session_2.EvaluateAsync( binding_2, L"" )
	
        auto stop = high_resolution_clock::now();
	    auto duration = duration_cast<microseconds>( stop - start );

	std::cout << "			Ending Evaluate			" << duration.count() << std::endl;

## Expected behavior

With only one evaluate call (let's assume only 	auto eval_1= session.EvaluateAsync(binding, L""(); between time recorded), I know duration is 10 ms.

If the EvaluateAsyn is truly asynchronous I expect with 2 calls, the time should be max of the 2 calls, however it takes double the time ie 20 ms to execute.

## Minimal reproduction of the problem with instructions

Environment

Windows Build Number: 18362.239

Visual Studio 
The newest 2019 enterprise version

**Comment by anagharao21** [comment]
Most of the examples for EvaluateAsync() are with C# await.

This does not show the difference between Evaluate and EvaluateAsync function calls.

It would be great to know the exact usage of "Asynchronous" term used in [Definition](https://docs.microsoft.com/en-us/uwp/api/windows.ai.machinelearning.learningmodelsession.evaluateasync?view=winrt-19041)

**Comment by smk2007** [comment]
Hi anagharao21,
Are you running CPU sessions, GPU sessions or a mix?

An Evaluate call will result in synchronous execution. At the end of the call the model will be evaluated, and the results will be ready for use.

An EvaluateAsync call will:
1) On CPU Device, it will create a background thread, and return immediately.
2) On GPU Device, it will queue all the work onto the GPU, and then return while the GPU processes the workload.

EXCEPTION: When you have a model that you are trying to run on a GPU Device, but the model has operators which are not available on the GPU, CPU fallback will occur. In this case, instead of queueing the work onto the GPU, the entire graph gets evaluated synchronously.

Let me know if this helps.

**Comment by martinb35** [comment]
@anagharao21 - thanks for your feedback. it's on our product backlog to make the documentation for async behavior better as it can get a bit complicated. For example, in addition to what @smk2007 said, there are also cases where running two evaluates asynchronously will be slower due to the internal multithreading of certain operators like Gemm and Conv. Those operators try to use all the threads, so if you have two threads that are trying to use Gemm, they will contend for the threads and can end up running slower than if you had just run them synchronously.
