### ISSUE TITLE
Microsoft Machine Learning getting sample sizes and other information

### ISSUE THREAD

**Issue by Spanner1969** [microsoft/Windows-Machine-Learning#346]
## Current behavior

When extracting the cluster information in C#, it is not possible to get the number of samples for each cluster and  it is not possible to get the withinss value (both of which can be accessed in R).

## Expected behavior

I would expect these values to be available.

## Minimal reproduction of the problem with instructions

https://docs.microsoft.com/en-us/answers/questions/74341/microsoft-machine-learning-getting-sample-sizes-an.html

## Environment

Windows Build Number:  Windows Server 2012 R2 Standard
Visual Studio 2017 15.9.4

**Comment by martinb35** [comment]
Hi @Spanner1969, sorry for the confusion, but I think you want to open your issue here: https://github.com/dotnet/machinelearning, which is the Microsoft ML.NET project that it seems you are using. We work with that team, but we are separate. For a description of what the Windows Machine Learning project is, see [here](https://github.com/microsoft/Windows-Machine-Learning#windows-ml).
