### ISSUE TITLE
Can't inference with tiny-yolov2 model because of shape mismatch in onnxruntime

### ISSUE THREAD

**Issue by raulsf6** [microsoft/Windows-Machine-Learning#374]
## I'm submitting a…

 Bug report (I searched for similar issues and did not find one)

## Current behavior

I'm trying to load a Tiny-Yolov2 model, which I got from [here](https://github.com/onnx/models/tree/master/vision/object_detection_segmentation/tiny-yolov2). When I try to execute this code to inference from an image:

```
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Windows.AI;
using Windows.AI.MachineLearning;
using Windows.Graphics.Imaging;
using Windows.Media;
using Windows.Storage;

namespace MachineLearningUWP
{
    class Detector
    {
        private LearningModel model;
        private LearningModelBinding binding;
        private ImageFeatureDescriptor inputImageDescriptor;
        private TensorFeatureDescriptor outputTensorDescriptor;
        private List<float> yoloResults;
        private LearningModelEvaluationResult results;
        private LearningModelSession session;

        public Detector()
        {
            yoloResults = new List<float>();
        }

        public async Task LoadModelAsync(string _modelFileName)
        {
            // Load and create the model
            var modelFile = await StorageFile.GetFileFromApplicationUriAsync(new Uri($"ms-appx:///Assets/{_modelFileName}"));
            model = await LearningModel.LoadFromStorageFileAsync(modelFile);

            //Get input and output features of the model
            List<ILearningModelFeatureDescriptor> inputFeatures = model.InputFeatures.ToList();
            List<ILearningModelFeatureDescriptor> outputFeatures = model.OutputFeatures.ToList();

            // Retrieve the first input feature which is an image
            inputImageDescriptor =
                    inputFeatures.FirstOrDefault(feature => feature.Kind == LearningModelFeatureKind.Image)
                    as ImageFeatureDescriptor;

            // Retrieve the first output feature which is a tensor
            outputTensorDescriptor =
                            outputFeatures.FirstOrDefault(feature => feature.Kind == LearningModelFeatureKind.Tensor)
                            as TensorFeatureDescriptor;

            // Create the evaluation session with the model
            session = new LearningModelSession(model);

            //Create binding and then bind input/output features
            binding = new LearningModelBinding(session);
        }
            


        public async Task<List<float>> EvaluateModelAsync(VideoFrame _inputFrame)
        {
            try
            {
                //Bind input and output
                binding.Bind(inputImageDescriptor.Name, _inputFrame);
                binding.Bind(outputTensorDescriptor.Name, yoloResults);

                //Evaluate and get the results
                var results = await session.EvaluateAsync(binding, "test");
                yoloResults = results.Outputs[outputTensorDescriptor.Name] as List<float>;
            }
            catch (Exception ex)
            {
                Console.WriteLine("Error: " + ex.Message);
            }

            return yoloResults;
        }
    }
}
```

I got this error:

```
Exception thrown at 0x759F46D2 (KernelBase.dll) in MachineLearningUWP.exe: WinRT originate error - 0x80004005 : 'onecoreuap\windows\windowsai\engine\lotus\onnxruntime\core\framework\execution_frame.cc:456 onnxruntime::VerifyShape tensor->Shape() == parameters.tensor_shape was false. MLValue shape verification failed. Current shape:{0,125,13,13} Requested shape:{1,125,13,13}'.
```

Actually, when I open my model in Netron I can see that his shape is [0,125,13,13]

![image](https://user-images.githubusercontent.com/28561912/104594811-fb291980-5671-11eb-8a23-86a68bab381c.png)

Is there a way to tell to onnxruntime to use the correct shape? Why it cannot detect the correct shape?

## Expected behavior

Correct inference of image with the model.

## Minimal reproduction of the problem with instructions

Execute the code above.

## Environment

Windows Build Number: 1909 18363.1256

App min and target version: 
![image](https://user-images.githubusercontent.com/28561912/104595907-8820a280-5673-11eb-870c-1ba9877fc165.png)

OS Version (Server, IoT Core, Desktop, etc): Desktop

Visual Studio 
- 2019 (version: 16.8.3)

**Comment by smk2007** [comment]
Hello raulsf6,
 
From what I can tell, the output binding is done with yoloResults, an empty List<float>(), and attempts to bind to an output tensor with a free batch dimension.

This corresponds to binding an IIterable<float> to a TensorFloat output.

So, 

1) CreateTensorValueFromInspectable in https://github.com/microsoft/onnxruntime/blob/master/winml/lib/Api/FeatureValues.h#L149
tries to CreateFromIterable(...) with the descriptor.Shape()

2) CreateFromIterable in https://github.com/microsoft/onnxruntime/blob/master/winml/lib/Api/impl/TensorBase.h#L447 attempts to calculate the missing batch dimension via GetAdjustedShape() and concludes that batch size is 0, because the tensor has no size to calculate it with.

3) Everything proceeds as normal, until the engine sees the shape with batch size set to 0, and errors out because it expects it to be 1 based on the input size.

In order to bind an output, when you dont know its shape, normally you would either:

1) Manually calculate the correct size of the IIterable<float>
2) Specify a placeholder via TensorFloat::Create()
3) Not bind anything and use unbound outputs. The output results will generate the unbound output for you!

Does that help?

**Comment by Adele101** [comment]
@raulsf6 please re-open if you have further questions on this topic.
