### ISSUE TITLE
Publish WinML Dashboard in Microsoft Store

### ISSUE THREAD

**Issue by lostmsu** [microsoft/Windows-Machine-Learning#378]
This would make it easier to install and then update automatically.

**Comment by Adele101** [comment]
Thank you for your request! The Windows ML team is taking this idea under consideration as we plan new features.

If there are others who have this feature request, please feel free to comment and let us know how it would be helpful for you.

**Comment by tiagoshibata** [comment]
Hey @lostmsu , thanks for the feature request. What do you use the dashboard for, and which features are the most important to you?

Publishing to the store would be hard for us due to store and UWP restrictions, so it's not something we would work on right now. But the entire app is compiled to JavaScript and can be run within a browser. We could keep the latest webapp hosted on GitHub pages (we used to have something like https://tiagoshibata.github.io/WinML-Dashboard/), so users could open it in a web browser and have the latest version running automatically. Would that help?

The one thing that wouldn't work is the converter, which runs on Python; there are ways to make it work by e.g. running a Python interpreter in webassembly, but it's not something we have done.

**Comment by lostmsu** [comment]
I don't use it often. I think my scenario was viewing the compute graph of a model.

**Comment by martinb35** [comment]
The team has taken this under consideration for future investments, but no plan to put the dashboard on the store in the near term, so closing this issue.
