### ISSUE TITLE
No suitable kernel definition found for op Gemm(9) (node Gemm_16)

### ISSUE THREAD

**Issue by btekin** [microsoft/Windows-Machine-Learning#392]
I'm deploying an ONNX model trained on PyTorch on a Windows 10 device (version 1903) for a UWP application (via Visual Studio). The model is a recurrent neural network with GRU units and I use [torch.onnx.export](https://pytorch.org/tutorials/advanced/super_resolution_with_onnxruntime.html) for converting the model. I use the Microsoft.AI.MachineLearning nuget package for WinML. Please find below the versions for the tools that I use and the onnx opset version:

OS: Windows 10, version 1903 (build 18362)
PyTorch: 1.8.1
Onnx opset version: 12
Onnx version: 1.9
Microsoft.AI.MachineLearning Nuget: 1.8.0
Microsoft Visual Studio: Enterprise 2019, Version 16.7.16

When I run the neural net on device, I can load the model but while trying to create a session, I come across the following runtime error: 

`No suitable kernel definition found for op Gemm(9) (node Gemm_16)`

Please also find here the neural net model visualized on Netron:

![image](https://user-images.githubusercontent.com/4387080/122082010-e8bd3280-cdff-11eb-8a93-c58cca78080e.png)

I've already tried different opset versions when saving the onnx model, none of them seems to work:
- For opset 9, I get an error when loading the model: "onecoreuap\windows\windowsai\winml\dll\mloperatorauthorimpl.cpp(2340)\Windows.AI.MachineLearning.dll!00007FFFC3FB37AC: (caller: 00007FFFC3FD16E4) Exception(1) tid(10d0) 80070057 The parameter is incorrect"
- For opset 10, I get an error when loading the model: 'Node: Slice_13 Node (Slice_13) has input size 4 not in range [min=1, max=1]'
- For opset 11, I receive exactly the same error as indicated above for opset version 12
- For opset 13, I get an error while loading the model: 'Node: Unsqueeze_5 Node (Unsqueeze_5) has input size 2 not in range [min=1, max=1]'

With all these models that use different opset versions, I can successfully carry out inference in Python using onnxruntime (version 1.8.0) though. 

Any pointers?

**Comment by smk2007** [comment]
Hi,

I noticed in your description that you mention that you are using the Microsoft.AI.MachineLearning NuGet package.
However, late you explain that you received an error complaining that "onecoreuap\windows\windowsai\winml\dll\mloperatorauthorimpl.cpp(2340)\Windows.AI.MachineLearning.dll!00007FFFC3FB37AC: (caller: 00007FFFC3FD16E4) Exception(1) tid(10d0) 80070057 The parameter is incorrect".

The Windows.AI.MachineLearning.dll is only loaded when running against the Windows SDK using the Windows.Ai.MachineLearning namespace. Since you are on 1903, opset 9 would not be available: https://docs.microsoft.com/en-us/windows/ai/windows-ml/onnx-versions

Can you confirm that you are using the Microsoft.AI.MachineLearning.dll via the Microsoft.AI.MachineLearning namespace? The 1.8 Microsoft.AI.MachineLearning NuGet Package has support for opset 12.

**Comment by nums11** [comment]
See the previous comment. Please reopen if you're still having issues.
