### ISSUE TITLE
pip install winmltools failure

### ISSUE THREAD

**Issue by shawncal** [Microsoft/Windows-Machine-Learning#56]
## I'm submitting a…
 - Bug report (I searched for similar issues and did not find one) 

## Current behavior

pip install winmltools

## Expected behavior

WinMLTools installs cleanly

## Minimal reproduction of the problem with instructions

On a fresh Win 10 install, install Python 3.7, Visual Studio 2017 with cmake extension
open VS command prompt and run "pip install winmltools"

Result: while installing the dependency package "onnx", hit the following error.

CMake Error at CMakeLists.txt:216 (message):
      Protobuf compiler not found

WinMLTools install fails. Problem can also be reproed with "pip install onnx"

## Environment

Windows Build Number: Windows 10, Version 1803, Build number 17134.285

OS Version (Server, IoT Core, Desktop, etc): Desktop

Visual Studio 
- [ ] 2017 (version: 15.8.3)

**Comment by kumraj** [comment]
reopen if the issue is not resolved

**Comment by joncamp** [comment]
I am seeing this on my box.
Ubuntu 20.04
Python 3.8.2

Seems like it is trying to grab onnx 1.5.0 rather than latest

$ pip show protobuf
Name: protobuf
Version: 3.6.1
Summary: Protocol Buffers
Home-page: https://developers.google.com/protocol-buffers/
Author: protobuf@googlegroups.com
Author-email: protobuf@googlegroups.com
License: 3-Clause BSD License
Requires: setuptools, six
Required-by: skl2onnx, onnxmltools, onnxconverter-common, onnx, keras2onnx
$ pip show onnx
Name: onnx
Version: 1.7.0
Summary: Open Neural Network Exchange
Home-page: https://github.com/onnx/onnx
Author: bddppq
Author-email: jbai@fb.com
License: UNKNOWN
Requires: six, numpy, typing-extensions, protobuf
Required-by: skl2onnx, onnxruntime, onnxmltools, onnxconverter-common, keras2onnx

$ pip install winmltools
Collecting winmltools
  Using cached winmltools-1.5.1-py2.py3-none-any.whl (40 kB)
Requirement already satisfied: numpy==1.16.4 in ./venv/lib/python3.8/site-packages (from winmltools) (1.16.4)
Collecting tf2onnx==1.5.3
  Using cached tf2onnx-1.5.3-py3-none-any.whl (145 kB)
Collecting onnx==1.5.0
  Using cached onnx-1.5.0.tar.gz (3.0 MB)
Requirement already satisfied: protobuf==3.6.1 in ./venv/lib/python3.8/site-packages (from winmltools) (3.6.1)
Collecting onnxmltools==1.5.1
  Using cached onnxmltools-1.5.1-py2.py3-none-any.whl (287 kB)
Requirement already satisfied: requests in ./venv/lib/python3.8/site-packages (from tf2onnx==1.5.3->winmltools) (2.23.0)
Requirement already satisfied: six in ./venv/lib/python3.8/site-packages (from tf2onnx==1.5.3->winmltools) (1.14.0)
Requirement already satisfied: typing-extensions>=3.6.2.1 in ./venv/lib/python3.8/site-packages (from onnx==1.5.0->winmltools) (3.7.4.2)
Requirement already satisfied: typing>=3.6.4 in ./venv/lib/python3.8/site-packages (from onnx==1.5.0->winmltools) (3.7.4.1)
Requirement already satisfied: setuptools in ./venv/lib/python3.8/site-packages (from protobuf==3.6.1->winmltools) (44.0.0)
Requirement already satisfied: skl2onnx in ./venv/lib/python3.8/site-packages (from onnxmltools==1.5.1->winmltools) (1.6.1)
Requirement already satisfied: keras2onnx in ./venv/lib/python3.8/site-packages (from onnxmltools==1.5.1->winmltools) (1.6.1)
Requirement already satisfied: onnxconverter-common>=1.5.0 in ./venv/lib/python3.8/site-packages (from onnxmltools==1.5.1->winmltools) (1.6.1)
Requirement already satisfied: chardet<4,>=3.0.2 in ./venv/lib/python3.8/site-packages (from requests->tf2onnx==1.5.3->winmltools) (3.0.4)
Requirement already satisfied: certifi>=2017.4.17 in ./venv/lib/python3.8/site-packages (from requests->tf2onnx==1.5.3->winmltools) (2020.4.5.1)
Requirement already satisfied: idna<3,>=2.5 in ./venv/lib/python3.8/site-packages (from requests->tf2onnx==1.5.3->winmltools) (2.9)
Requirement already satisfied: urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 in ./venv/lib/python3.8/site-packages (from requests->tf2onnx==1.5.3->winmltools) (1.25.9)
Requirement already satisfied: scikit-learn>=0.19 in ./venv/lib/python3.8/site-packages (from skl2onnx->onnxmltools==1.5.1->winmltools) (0.22.2.post1)
Requirement already satisfied: fire in ./venv/lib/python3.8/site-packages (from keras2onnx->onnxmltools==1.5.1->winmltools) (0.3.1)
Requirement already satisfied: joblib>=0.11 in ./venv/lib/python3.8/site-packages (from scikit-learn>=0.19->skl2onnx->onnxmltools==1.5.1->winmltools) (0.14.1)
Requirement already satisfied: scipy>=0.17.0 in ./venv/lib/python3.8/site-packages (from scikit-learn>=0.19->skl2onnx->onnxmltools==1.5.1->winmltools) (1.4.1)
Requirement already satisfied: termcolor in ./venv/lib/python3.8/site-packages (from fire->keras2onnx->onnxmltools==1.5.1->winmltools) (1.1.0)
Building wheels for collected packages: onnx
  Building wheel for onnx (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: /home/somedir/pytorch/venv/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-b5e4djak/onnx/setup.py'"'"'; __file__='"'"'/tmp/pip-install-b5e4djak/onnx/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-k44r5woc
       cwd: /tmp/pip-install-b5e4djak/onnx/
  Complete output (63 lines):
  fatal: not a git repository (or any of the parent directories): .git
  running bdist_wheel
  running build
  running build_py
  running create_version
  running cmake_build
  -- The C compiler identification is GNU 9.3.0
  -- The CXX compiler identification is GNU 9.3.0
  -- Check for working C compiler: /usr/bin/cc
  -- Check for working C compiler: /usr/bin/cc - works
  -- Detecting C compiler ABI info
  -- Detecting C compiler ABI info - done
  -- Detecting C compile features
  -- Detecting C compile features - done
  -- Check for working CXX compiler: /usr/bin/c++
  -- Check for working CXX compiler: /usr/bin/c++ - works
  -- Detecting CXX compiler ABI info
  -- Detecting CXX compiler ABI info - done
  -- Detecting CXX compile features
  -- Detecting CXX compile features - done
  CMake Error at CMakeLists.txt:226 (message):
    Protobuf compiler not found
  Call Stack (most recent call first):
    CMakeLists.txt:257 (relative_protobuf_generate_cpp)
  
  
  -- Configuring incomplete, errors occurred!
  See also "/tmp/pip-install-b5e4djak/onnx/.setuptools-cmake-build/CMakeFiles/CMakeOutput.log".
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "/tmp/pip-install-b5e4djak/onnx/setup.py", line 312, in <module>
      setuptools.setup(
    File "/home/somedir/pytorch/venv/lib/python3.8/site-packages/setuptools/__init__.py", line 145, in setup
      return distutils.core.setup(**attrs)
    File "/usr/lib/python3.8/distutils/core.py", line 148, in setup
      dist.run_commands()
    File "/usr/lib/python3.8/distutils/dist.py", line 966, in run_commands
      self.run_command(cmd)
    File "/usr/lib/python3.8/distutils/dist.py", line 985, in run_command
      cmd_obj.run()
    File "/home/somedir/pytorch/venv/lib/python3.8/site-packages/wheel/bdist_wheel.py", line 223, in run
      self.run_command('build')
    File "/usr/lib/python3.8/distutils/cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "/usr/lib/python3.8/distutils/dist.py", line 985, in run_command
      cmd_obj.run()
    File "/usr/lib/python3.8/distutils/command/build.py", line 135, in run
      self.run_command(cmd_name)
    File "/usr/lib/python3.8/distutils/cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "/usr/lib/python3.8/distutils/dist.py", line 985, in run_command
      cmd_obj.run()
    File "/tmp/pip-install-b5e4djak/onnx/setup.py", line 206, in run
      self.run_command('cmake_build')
    File "/usr/lib/python3.8/distutils/cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "/usr/lib/python3.8/distutils/dist.py", line 985, in run_command
      cmd_obj.run()
    File "/tmp/pip-install-b5e4djak/onnx/setup.py", line 192, in run
      subprocess.check_call(cmake_args)
    File "/usr/lib/python3.8/subprocess.py", line 364, in check_call
      raise CalledProcessError(retcode, cmd)
  subprocess.CalledProcessError: Command '['/home/somedir/pytorch/venv/bin/cmake', '-DPYTHON_INCLUDE_DIR=/usr/include/python3.8', '-DPYTHON_EXECUTABLE=/home/somedir/pytorch/venv/bin/python3', '-DBUILD_ONNX_PYTHON=ON', '-DCMAKE_EXPORT_COMPILE_COMMANDS=ON', '-DONNX_NAMESPACE=onnx', '-DPY_EXT_SUFFIX=.cpython-38-x86_64-linux-gnu.so', '-DCMAKE_BUILD_TYPE=Release', '-DONNX_ML=1', '/tmp/pip-install-b5e4djak/onnx']' returned non-zero exit status 1.
  ----------------------------------------
  ERROR: Failed building wheel for onnx
  Running setup.py clean for onnx
Failed to build onnx
ERROR: onnxruntime 1.2.0 has requirement numpy>=1.18.0, but you'll have numpy 1.16.4 which is incompatible.
Installing collected packages: onnx, tf2onnx, onnxmltools, winmltools
  Attempting uninstall: onnx
    Found existing installation: onnx 1.7.0
    Uninstalling onnx-1.7.0:
      Successfully uninstalled onnx-1.7.0
    Running setup.py install for onnx ... error
    ERROR: Command errored out with exit status 1:
     command: /home/somedir/pytorch/venv/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-b5e4djak/onnx/setup.py'"'"'; __file__='"'"'/tmp/pip-install-b5e4djak/onnx/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-az11oau3/install-record.txt --single-version-externally-managed --compile --install-headers /home/somedir/pytorch/venv/include/site/python3.8/onnx
         cwd: /tmp/pip-install-b5e4djak/onnx/
    Complete output (51 lines):
    fatal: not a git repository (or any of the parent directories): .git
    running install
    running build
    running build_py
    running create_version
    running cmake_build
    CMake Error at CMakeLists.txt:226 (message):
      Protobuf compiler not found
    Call Stack (most recent call first):
      CMakeLists.txt:257 (relative_protobuf_generate_cpp)
    
    
    -- Configuring incomplete, errors occurred!
    See also "/tmp/pip-install-b5e4djak/onnx/.setuptools-cmake-build/CMakeFiles/CMakeOutput.log".
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-b5e4djak/onnx/setup.py", line 312, in <module>
        setuptools.setup(
      File "/home/somedir/pytorch/venv/lib/python3.8/site-packages/setuptools/__init__.py", line 145, in setup
        return distutils.core.setup(**attrs)
      File "/usr/lib/python3.8/distutils/core.py", line 148, in setup
        dist.run_commands()
      File "/usr/lib/python3.8/distutils/dist.py", line 966, in run_commands
        self.run_command(cmd)
      File "/usr/lib/python3.8/distutils/dist.py", line 985, in run_command
        cmd_obj.run()
      File "/home/somedir/pytorch/venv/lib/python3.8/site-packages/setuptools/command/install.py", line 61, in run
        return orig.install.run(self)
      File "/usr/lib/python3.8/distutils/command/install.py", line 589, in run
        self.run_command('build')
      File "/usr/lib/python3.8/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/usr/lib/python3.8/distutils/dist.py", line 985, in run_command
        cmd_obj.run()
      File "/usr/lib/python3.8/distutils/command/build.py", line 135, in run
        self.run_command(cmd_name)
      File "/usr/lib/python3.8/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/usr/lib/python3.8/distutils/dist.py", line 985, in run_command
        cmd_obj.run()
      File "/tmp/pip-install-b5e4djak/onnx/setup.py", line 206, in run
        self.run_command('cmake_build')
      File "/usr/lib/python3.8/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/usr/lib/python3.8/distutils/dist.py", line 985, in run_command
        cmd_obj.run()
      File "/tmp/pip-install-b5e4djak/onnx/setup.py", line 192, in run
        subprocess.check_call(cmake_args)
      File "/usr/lib/python3.8/subprocess.py", line 364, in check_call
        raise CalledProcessError(retcode, cmd)
    subprocess.CalledProcessError: Command '['/home/somedir/pytorch/venv/bin/cmake', '-DPYTHON_INCLUDE_DIR=/usr/include/python3.8', '-DPYTHON_EXECUTABLE=/home/somedir/pytorch/venv/bin/python3', '-DBUILD_ONNX_PYTHON=ON', '-DCMAKE_EXPORT_COMPILE_COMMANDS=ON', '-DONNX_NAMESPACE=onnx', '-DPY_EXT_SUFFIX=.cpython-38-x86_64-linux-gnu.so', '-DCMAKE_BUILD_TYPE=Release', '-DONNX_ML=1', '/tmp/pip-install-b5e4djak/onnx']' returned non-zero exit status 1.
    ----------------------------------------
  Rolling back uninstall of onnx
  Moving to /home/somedir/pytorch/venv/bin/backend-test-tools
   from /tmp/pip-uninstall-y6ckz9mu/backend-test-tools
  Moving to /home/somedir/pytorch/venv/bin/check-model
   from /tmp/pip-uninstall-y6ckz9mu/check-model
  Moving to /home/somedir/pytorch/venv/bin/check-node
   from /tmp/pip-uninstall-y6ckz9mu/check-node
  Moving to /home/somedir/pytorch/venv/lib/python3.8/site-packages/onnx-1.7.0.dist-info/
   from /home/somedir/pytorch/venv/lib/python3.8/site-packages/~nnx-1.7.0.dist-info
  Moving to /home/somedir/pytorch/venv/lib/python3.8/site-packages/onnx.libs/
   from /home/somedir/pytorch/venv/lib/python3.8/site-packages/~nnx.libs
  Moving to /home/somedir/pytorch/venv/lib/python3.8/site-packages/onnx/
   from /home/somedir/pytorch/venv/lib/python3.8/site-packages/~nnx
ERROR: Command errored out with exit status 1: /home/somedir/pytorch/venv/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-b5e4djak/onnx/setup.py'"'"'; __file__='"'"'/tmp/pip-install-b5e4djak/onnx/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-az11oau3/install-record.txt --single-version-externally-managed --compile --install-headers /home/somedir/pytorch/venv/include/site/python3.8/onnx Check the logs for full command output.

**Comment by zhangxiang1993** [comment]
WinMLTools doesn't support python 3.8 so far, because it fixes the dependency on onnx 1.5.0 which does not support python 3.8.
